### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by TravisEz13** [RicoSuter/Namotion.Reflection#10]

**Comment by RicoSuter** [comment]
May i ask: What are you using this lib for?

**Comment by TravisEz13** [comment]
This is used with NJsonSchema.  Without a license, on either the package on the source.  I will need to replace NJsonSchema with something that has a license.

**Comment by TravisEz13** [comment]
@RicoSuter I think I misread your question.  I'm acting as maintainer of PowerShell/PowerShell, and 
 see preview https://github.com/RicoSuter/Namotion.Reflection/issues/10#issuecomment-505545968

**Comment by RicoSuter** [comment]
I’ll also update the package with the license, is that enough for you?

**Comment by TravisEz13** [comment]
Yeah, I'll get back to you if legal has any more questions, but with MIT there aren't usually any issues.
