### ISSUE TITLE
Sources for the 2.1.2 nuget package

### ISSUE THREAD

**Issue by evegufy** [RicoSuter/Namotion.Reflection#131]
First of all, thank you for providing this library!

Could you please provide a released or tagged source of the 2.1.2  nuget package (https://www.nuget.org/packages/Namotion.Reflection/2.1.2)?

Thank you in advance!

**Comment by RicoSuter** [comment]
https://github.com/RicoSuter/Namotion.Reflection/releases/tag/v2.1.2
