### ISSUE TITLE
Upgrading from 3.0.1 to 3.1.0 breaks NSwag documentation

### ISSUE THREAD

**Issue by 64Soft** [RicoSuter/Namotion.Reflection#139]
When upgrading from Namotion.Reflection package 3.0.1 to 3.1.0, something broke when generating the documentation page using UseSwaggerUi3 with NSwag

This is my code for calling UseSwaggerUi3, pretty basic, and worked fine with Namotion.Reflection 3.0.1

`app.UseSwaggerUi3(typeof(Startup).Assembly, settings =>
{
    settings.GeneratorSettings.Title = "MyApi";
});`

However after updating to 3.1.0, the documentation page yields a 500 error:

![image](https://github.com/RicoSuter/Namotion.Reflection/assets/3592524/82103323-645e-406c-9d80-8332f2149109)

Downgrading to 3.0.1 makes it work again.

Any settings I should change in the UseSwaggerUi3 parameters ?

I'm using .NET Framework 4.7.2 for this project.

Thanks

**Comment by Scorpoon** [comment]
Same here.
Errormessage is `Method not found: "System.Attribute[] Namotion.Reflection.ContextualType.get_ContextAttributes()".`
