### ISSUE TITLE
Get nullability of array element type or ContextualType of array element type

### ISSUE THREAD

**Issue by dbolin** [RicoSuter/Namotion.Reflection#14]
Given a field declaration such as `public string?[] Array;` there doesn't appear to be a way to get the nullability of the element type, as opposed to the array itself.  I might have missed it, but I couldn't find anything that would let me get it anywhere.

I also need to do this for nested arrays like `public string?[]?[] Array;` - so I'd actually prefer an equivalent to Type.GetElementType() that returns a ContextualType for the element type, rather than just getting the nullability of the element type, as that would allow me to traverse all element types of nested arrays, including more complex elements that have generic arguments.

**Comment by RicoSuter** [comment]
Shouldnt be hard to add..

**Comment by RicoSuter** [comment]
Added a PR, but the test seems wrong: 

https://github.com/RicoSuter/Namotion.Reflection/pull/15/files#diff-0fb3f7295028c6d581034a850b425c0eR50

What do you think?

**Comment by dbolin** [comment]
Looks good to me - why does it seem wrong?

**Comment by RicoSuter** [comment]
The order seems wrong but maybe its just my lack of understanding of multi dimension arrays... so the pr is fine for you?

**Comment by dbolin** [comment]
That's the right order, so yep, the PR does everything I need right now.
