### ISSUE TITLE
Nullability Unknown when in reality it is known

### ISSUE THREAD

**Issue by shoe-diamente** [RicoSuter/Namotion.Reflection#16]
Seeing this screenshot of the debugger for the latest .NET Core 3 preview and C# 8.0 enabled I see this:

![Screen Shot 2019-07-31 at 16 39 07](https://user-images.githubusercontent.com/40760781/62221376-dd022780-b3b1-11e9-985b-4ceb9cdeb7cd.png)
 
As you can see there's the `NullableAttribute` and it has `NullableFlags`. It just seems to not detect those.

I'm using Namotion.Reflection 1.0.5.

**Comment by RicoSuter** [comment]
1.0.5 is based on an old compiler version.. please quickly try the latest preview version. Will release v1.0.6 soon

**Comment by shoe-diamente** [comment]
I'm sorry, how do I add the preview? I registered an account for MyGet but the interface changed since the last time I've used it.

**Comment by shoe-diamente** [comment]
Seems like I've solved it with:

```
dotnet add package Namotion.Reflection --version 1.0.6-20190731.3 --source https://www.myget.org/F/namotion-reflection/api/v3/index.json
```

It doesn't change the result though.

**Comment by RicoSuter** [comment]
Can you post an example and the expected output?

**Comment by shoe-diamente** [comment]
Sure.

If you run [this test](https://github.com/shoe-diamente/conventions/blob/nrt/test/Tests/Adapters/TypeConstructionTests.cs#L121) and set a breakpoint [here](https://github.com/shoe-diamente/conventions/blob/nrt/src/GraphQL.Conventions/Types/Resolution/ObjectReflector.cs#L83) you'll see the result described in the image above.

In that case I would expect the `Nullability` parameter of the `ContextualPropertyInfo` to be anything other than `Unknown`.

**Comment by shoe-diamente** [comment]
This was not the library's fault.
