### ISSUE TITLE
Regression from https://github.com/RicoSuter/NSwag/issues/899

### ISSUE THREAD

**Issue by daniel-white** [RicoSuter/Namotion.Reflection#22]
It appears that this library which I'm assuming NJsonSchema and NSwag is now using has regressed the fix for: https://github.com/RicoSuter/NSwag/issues/899

NSwag/NJsonSchema isn't outputing the xml documentation into my openapi document.

**Comment by RicoSuter** [comment]
Is this still an issue?

**Comment by daniel-white** [comment]
yea i have  v13.2.2.0 of NSwag and it doesn't seem to be working. iirc, i diffed the NJsonSchema class and it look like the fix for that 899 issue is present.

**Comment by daniel-white** [comment]
See https://github.com/RicoSuter/Namotion.Reflection/blob/master/src/Namotion.Reflection/XmlDocsExtensions.cs#L639

**Comment by daniel-white** [comment]
Never mind. PEBKAC here.
