### ISSUE TITLE
EnsureValidNullability doesn't work(?)

### ISSUE THREAD

**Issue by ProductiveRage** [RicoSuter/Namotion.Reflection#24]
I've tried to come up with the simplest example to test how the `EnsureValidNullability` extension method would work - I would expect it to throw in the following code because the "Name" property of the `PersonDetails` is a string and `#nullable enable` is specified for the file and the value in the JSON is null:

```
#nullable enable

using System;
using Namotion.Reflection;
using Newtonsoft.Json;

namespace Tester
{
    static class Program
    {
        static void Main()
        {
            var json = "{ \"ID\": 123, \"Name\": null }";
            var p = JsonConvert.DeserializeObject<PersonDetails>(json);
            p.EnsureValidNullability();
            Console.WriteLine("Shouldn't get here - line above should throw");
        }
    }

    public sealed class PersonDetails
    {
        public PersonDetails(int id, string name)
        {
            ID = id;
            Name = name;
        }
        public int ID { get; }
        public string Name { get; }
    }
}
```

I've recreated this using .NET Fiddle to try to make it as quick and easy to reproduce: [dotnetfiddle.net/fmha4i](https://dotnetfiddle.net/fmha4i)

**Comment by RicoSuter** [comment]
Strange, i’d expect this to work. Are NRT really enabled?

**Comment by ProductiveRage** [comment]
I originally encountered this in a project where I enabled NRT in the project file but moved it to be file scoped to make this repro case more succinct. In both cases, Visual Studio would show a warning if I included code that manually new'd up a PersonDetails instance with a null name and so I think that NRT must indeed have been successfully enabled.

**Comment by RicoSuter** [comment]
Couldnt find a problem, can you repro this in a test in the sln?

**Comment by ProductiveRage** [comment]
You didn't explicitly mention, but did you try the "dotnetfiddle" link that I included in my original comment? Because this is a self-contained and fully executable reproduce case where you can clearly see at the top of the file "#nullable enable". I have just re-tried that link to ensure that nothing has changed and nothing _has_ changed, it still does not work.

However, as requested, I have also taken that code and created a new unit test to illustrate the problem - essentially using the same code from the dotnetfiddle example. You can find it in the following pull request:

https://github.com/RicoSuter/Namotion.Reflection/pull/31

**Comment by RicoSuter** [comment]
I tried it yes, but i need to reproduce this in my sln so that i can debug it etc.

**Comment by RicoSuter** [comment]
v1.0.10
