### ISSUE TITLE
Nested types can incorrectly show Unknown instead of NotNullable for properties

### ISSUE THREAD

**Issue by ProductiveRage** [RicoSuter/Namotion.Reflection#25]
The following code works as expected, it outputs "PersonDetails.Name.Nullability: NotNullable" -

```
#nullable enable

using System;
using Namotion.Reflection;

namespace Tester
{
    static class Program
    {
        static void Main()
        {
            Console.WriteLine("PersonDetails.Name.Nullability: " + typeof(PersonDetails).GetContextualProperties()[0].Nullability);
        }

        public sealed class PersonDetails
        {
            public PersonDetails(string name) => Name = name;
            public string Name { get; }
        }
    }
}
```

(See [dotnetfiddle.net/Jqdk7S](https://dotnetfiddle.net/Jqdk7S))

However, if I add a second nested classed with `Program` then the output becomes "PersonDetails.Name.Nullability: Unknown" -

```
#nullable enable

using System;
using Namotion.Reflection;

namespace Tester
{
    static class Program
    {
        static void Main()
        {
            Console.WriteLine("PersonDetails.Name.Nullability: " + typeof(PersonDetails).GetContextualProperties()[0].Nullability);
        }

        public sealed class PersonDetails
        {
            public PersonDetails(string name) => Name = name;
            public string Name { get; }
        }

        public sealed class RoleDetails
        {
            public RoleDetails(string name) => Name = name;
            public string Name { get; }
        }
    }
}
```

(See [dotnetfiddle.net/9rYIow](https://dotnetfiddle.net/9rYIow))

Looking at the attributes that the compiler generates for these, it seems to remove the `[NullableContext]` attribute from the `PersonDetails` class in the second version and append it to the `Program` class, though it leaves the `[Nullable]` on `PersonDetails` - I've started reading through your explanations of these attributes but I don't understand enough yet to be able to tell whether this could be causing the problem!

![image](https://user-images.githubusercontent.com/742348/71594773-1ab9d680-2b31-11ea-9be2-466143e891ea.png)

![image](https://user-images.githubusercontent.com/742348/71594779-22797b00-2b31-11ea-8529-22f0ba34fc64.png)

**Comment by RicoSuter** [comment]
v1.0.10
