### ISSUE TITLE
C# 8 nullable inside array not taken into account

### ISSUE THREAD

**Issue by jeremyVignelles** [RicoSuter/Namotion.Reflection#36]
Disclaimer: I only tested in NSwag, but I assume that the root cause is in NJSonSchema. Since I don't know how things works here, I did not test in NJS. Feel free to move the issue if it doesn't belong here.

This is a continuation of https://github.com/RicoSuter/NSwag/issues/1951

After implementing my property like this:

```cs
        [JsonProperty(Required = Required.Always)]
        [ItemsCanBeNull]
        public string[] NullableStrings { get; set; } = {"Hello", null, "World"};
```

It is working as I expected, but now, I'm trying to migrate my code with C#8 nullables, so I tried to do that:

```cs
        [JsonProperty(Required = Required.Always)]
        public string?[] NullableStrings { get; set; } = {"Hello", null, "World"};
```

But it doesn't generate the nullability information properly, while it does on a plain `string?` property.

Repro : https://github.com/jeremyVignelles/TestNSwagNetCoreApp/blob/repro/array-of-nullables2/TestNSwagNetCoreApp/Hello.cs#L60

**Comment by RicoSuter** [comment]
The issue has been transferred. Can you create a PR with a repro (and maybe a fix)?

**Comment by jeremyVignelles** [comment]
Not sure I will find time to look into that soon

**Comment by RicoSuter** [comment]
Sure, if I have time (and it seems so in these times) I can look into. NRT is still not complete as there are quite some edge cases which might not work or which need some sort of workaround.

**Comment by jeremyVignelles** [comment]
With Namotion.Reflection, I can properly retrieve the nullability with this:

```cs
arrayType.ElementType.Nullability
```

The issue seems to be at a higher level. The generated OpenApi spec is not valid :
```json
          "nullableStrings": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
```

expected:

```json
          "nullableStrings": {
            "type": "array",
            "items": {
              "type": "string",
              "nullable": true
            }
          },
```

**Comment by RicoSuter** [comment]
Now we need to ensure we use the new reflection property everywhere and not the extension method.
