### ISSUE TITLE
Nullability not obtained for generic arguments of base type

### ISSUE THREAD

**Issue by adamjones1** [RicoSuter/Namotion.Reflection#46]
I'm interested in observing the nullability attributes of a type like `Derived` in
```
public class MyBase<T> { }
public class Derived : MyBase<string?> { }
```
In this case `NullableAttribute` for the `string?` [is directly placed on the `Derived` type](https://sharplab.io/#v2:CYLg1APgAgzABFATHAsgTwEIEMDOBTAHgBUA+OAbzgF8BYAKFgWQBE8AnASwDc9g4RUmXISgBGAAwB+MpSpA).

I tried calling `ToContextualMember` and `ToContextualType` on `typeof(Derived)` but neither appear to expose this information - correct me if I'm wrong but it seems like this functionality isn't present in the library yet. I propose we add it and can contribute time to expedite this.

**Comment by adamjones1** [comment]
FWIW I was able to work around this using
```
public static ContextualTypeExtensions
{
    public static ContextualType GetBaseType(this ContextualType type)
    {
        var ot = type.OriginalType;
        return ot.BaseType.ToContextualType(ot.GetCustomAttributes());
    }
}
```

Though it would still be nice if this were made part of the library as a property to save someone else the trouble of figuring it out.

**Comment by RicoSuter** [comment]
I’d expect that the base type is a contextual type with an array of contextual generic type arguments with this info, is this not the case? If not it would be nice to fix this..

**Comment by adamjones1** [comment]
I don't think the base type is exposed at all, you have to manually construct it from the derived using the above excerpt. Should just be a matter of adding a `BaseType` property with this implementation to `ContextualType`.
