### ISSUE TITLE
Possible bug when locating XML file

### ISSUE THREAD

**Issue by bert2** [RicoSuter/Namotion.Reflection#50]
I may have found a bug by chance while looking through the source. I think the path constructed below should be checked with `DynamicApis.FileExists(path)` before returning it.

https://github.com/RicoSuter/Namotion.Reflection/blob/486001ebe8d488fb145c9bd71af0f7457c412dae/src/Namotion.Reflection/XmlDocsExtensions.cs#L709

But maybe I'm misunderstanding something. In that case this issue can be closed.

**Comment by RicoSuter** [comment]
Maybe adding the check is a good idea. It surely doesnt hurt. Can you create a PR?

**Comment by bert2** [comment]
The effect is that the library will never look for XML docs in the working directory (i.e. `.\<assembly>.xml` and `.\bin\<assembly>.xml`). A pretty wild edge case, I guess, but nevertheless unintended behavior.

Gonna make a PR.

**Comment by RicoSuter** [comment]
Merged and released as v1.0.16
