### ISSUE TITLE
C# 9 Record properties XML Documentation not carrying over the the generated property description

### ISSUE THREAD

**Issue by hrkeni** [RicoSuter/Namotion.Reflection#73]
C# 9 records are documented this way:

```
    /// <summary>
    /// Returns a list of items.
    /// </summary>
    /// <param name="PageNumber">The page number.</param>
    /// <param name="PageSize">The page size.</param>
    public record ListItems(int PageNumber, int PageSize);
```

The expectation would be that the `<param>` documentation would carry over into the `description` of the property when the schema is generated.

**Comment by RicoSuter** [comment]
Needs to be fixed here: 
https://github.com/RicoSuter/Namotion.Reflection/blob/master/src/Namotion.Reflection/XmlDocsExtensions.cs
