### ISSUE TITLE
Make XmlDocsExtensions.GetXmlDocsPath public

### ISSUE THREAD

**Issue by erichiller** [RicoSuter/Namotion.Reflection#75]
It would be great if I could easily access the functionality behind `XmlDocsExtensions.cs` / `private string GetXmlDocsPath(dynamic assembly)`.

**Comment by RicoSuter** [comment]
Fine for me... we probably should change "dynamic" to "Assembly" if possible (need to check the reason for that).

**Comment by erichiller** [comment]
Sorry for the delay, I started working on this - quick question, do you have desired style settings, or should I just use my preference?

**Comment by RicoSuter** [comment]
This should be a very small change no?
I'd try to align style with the rest of the code...

**Comment by erichiller** [comment]
Sorry for the delay. I added some other functionality around using `<inheritdoc cref="' />`. PR #83 
Let me know if anything looks off!
